_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 100
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
                - 100
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
batch_size:
    value: 128
epochs:
    value: 50
learning_rate:
    value: 0.1
